name: Review

on:
  pull_request:
    paths:
      - '*/src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/review.yml'

env:
  CARGO_INCREMENTAL: 0

jobs:
  rust:
    strategy:
      matrix:
        include:
          - ghimage: ubuntu-24.04
            dockerarch: linux/amd64
            rustfscliarch: amd64

    permissions:
      checks: write

    runs-on: ${{ matrix.ghimage }}

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Get Rust toolchain
        id: toolchain
        run: |
          awk -F'[ ="]+' '$1 == "channel" { print "toolchain=" $2 }' rust-toolchain >> "$GITHUB_OUTPUT"

      - name: install clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
          components: clippy

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.9.1

      - name: clippy check
        uses: yanorei32/action-clippy@50412b135153ebee7d4b8a5b868c4defdc663683
        with:
          reporter: github-pr-review

      - name: cargo check
        run: |
          cargo check
